name: Builds, tests & co

on:
  push:
  pull_request:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "4.14"
          - "5.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true

      - run: brew install postgresql@14
        if: ${{ runner.os == 'macOS' }}

      - run: opam pin add mingw-w64-shims git+https://github.com/dra27/mingw-w64-shims.git#internals
        if: ${{ runner.os == 'Windows' }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build @all

      - run: opam exec -- dune runtest

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: "5.2"

      - uses: kit-ty-kate/setup-ocaml/lint-opam@win52

  lint-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: "5.2"
          dune-cache: true

      - uses: kit-ty-kate/setup-ocaml/lint-doc@win52
